#-*- encoding: utf-8; mode: yaml -*-

#=========================================================================
# Copyright (c) 2015 Matt Bogosian <mtb19@columbia.edu>.
#
# Please see the accompanying LICENSE (or LICENSE.txt) file for rights and
# restrictions governing use of this software. All rights not expressly
# waived or licensed are reserved. If such a file did not accompany this
# software, then please contact the author before viewing or using this
# software in any capacity.
#=========================================================================

language: python
python: "3.4"

install:
    - pip install coveralls tox

# Grrr... <https://github.com/travis-ci/travis-ci/issues/1519> is closed
# without a fix
env:
    - TOX_ENV=py27 TWISTED='Twisted == 15.3'
    - TOX_ENV=py27 TWISTED='Twisted == 15.3' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
    - TOX_ENV=py27 TWISTED='Twisted == 15.4'
    - TOX_ENV=py27 TWISTED='Twisted == 15.4' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
    - TOX_ENV=py27 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
    - TOX_ENV=py27 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography

    - TOX_ENV=pypy TWISTED='Twisted == 15.3'
    - TOX_ENV=pypy TWISTED='Twisted == 15.3' OPENSSL=pyOpenSSL CRYPTOGRAPHY='cryptography < 1.0'
    - TOX_ENV=pypy TWISTED='Twisted == 15.4'
    - TOX_ENV=pypy TWISTED='Twisted == 15.4' OPENSSL=pyOpenSSL CRYPTOGRAPHY='cryptography < 1.0'
    - TOX_ENV=pypy TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
    - TOX_ENV=pypy TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk OPENSSL=pyOpenSSL CRYPTOGRAPHY='cryptography < 1.0'

    - TOX_ENV=py33 TWISTED='Twisted == 15.3'
    - TOX_ENV=py33 TWISTED='Twisted == 15.3' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
    - TOX_ENV=py33 TWISTED='Twisted == 15.4'
    - TOX_ENV=py33 TWISTED='Twisted == 15.4' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
    - TOX_ENV=py33 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
    - TOX_ENV=py33 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography

    - TOX_ENV=py34 TWISTED='Twisted == 15.3'
    - TOX_ENV=py34 TWISTED='Twisted == 15.3' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
    - TOX_ENV=py34 TWISTED='Twisted == 15.4'
    - TOX_ENV=py34 TWISTED='Twisted == 15.4' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
    - TOX_ENV=py34 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
    - TOX_ENV=py34 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography

matrix:
    allow_failures:
        - env: TOX_ENV=py27 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
        - env: TOX_ENV=py27 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography

        - env: TOX_ENV=pypy TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
        - env: TOX_ENV=pypy TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk OPENSSL=pyOpenSSL CRYPTOGRAPHY='cryptography < 1.0'

        - env: TOX_ENV=py33 TWISTED='Twisted == 15.3'
        - env: TOX_ENV=py33 TWISTED='Twisted == 15.3' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
        - env: TOX_ENV=py33 TWISTED='Twisted == 15.4'
        - env: TOX_ENV=py33 TWISTED='Twisted == 15.4' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
        - env: TOX_ENV=py33 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
        - env: TOX_ENV=py33 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography

        - env: TOX_ENV=py34 TWISTED='Twisted == 15.3'
        - env: TOX_ENV=py34 TWISTED='Twisted == 15.3' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
        - env: TOX_ENV=py34 TWISTED='Twisted == 15.4'
        - env: TOX_ENV=py34 TWISTED='Twisted == 15.4' OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography
        - env: TOX_ENV=py34 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
        - env: TOX_ENV=py34 TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk OPENSSL=pyOpenSSL CRYPTOGRAPHY=cryptography

script:
    - tox -e "${TOX_ENV}"
    - ./runintegrations.sh

after_success:
    - coveralls
