#-*- encoding: utf-8; mode: yaml -*-

#=========================================================================
# Copyright (c) 2015 Matt Bogosian <mtb19@columbia.edu>.
#
# Please see the accompanying LICENSE (or LICENSE.txt) file for rights and
# restrictions governing use of this software. All rights not expressly
# waived or licensed are reserved. If such a file did not accompany this
# software, then please contact the author before viewing or using this
# software in any capacity.
#=========================================================================

language: python
python: "3.4"

install:
    - pip install coveralls tox

# Grrr; <https://github.com/travis-ci/travis-ci/issues/1519> is closed
# without a fix
env:
    - TOX_ENV=py27-twisted_15_3-ssl_no
    - TOX_ENV=py27-twisted_15_3-ssl_yes
    - TOX_ENV=py27-twisted_15_3-ssl_yes TEST_DEADLOCK=1 TEST_INSIGHT=1
    - TOX_ENV=py27-twisted_15_4-ssl_no
    - TOX_ENV=py27-twisted_15_4-ssl_yes
    - TOX_ENV=py27-twisted_15_4-ssl_yes TEST_DEADLOCK=1 TEST_INSIGHT=1
    - TOX_ENV=py27-twisted_trunk-ssl_no
    - TOX_ENV=py27-twisted_trunk-ssl_yes

    - TOX_ENV=pypy-twisted_15_3-ssl_no
    - TOX_ENV=pypy-twisted_15_3-ssl_yes
    - TOX_ENV=pypy-twisted_15_4-ssl_no
    - TOX_ENV=pypy-twisted_15_4-ssl_yes
    - TOX_ENV=pypy-twisted_trunk-ssl_no
    - TOX_ENV=pypy-twisted_trunk-ssl_yes

    - TOX_ENV=py33-twisted_trunk-ssl_no
    - TOX_ENV=py33-twisted_trunk-ssl_yes

    - TOX_ENV=py34-twisted_trunk-ssl_no
    - TOX_ENV=py34-twisted_trunk-ssl_yes

matrix:
    allow_failures:
        - env: TOX_ENV=py27-twisted_15_3-ssl_yes TEST_DEADLOCK=1 TEST_INSIGHT=1
        - env: TOX_ENV=py27-twisted_15_4-ssl_yes TEST_DEADLOCK=1 TEST_INSIGHT=1

        # Twisted trunk is experimental
        - env: TOX_ENV=py27-twisted_trunk-ssl_no
        - env: TOX_ENV=py27-twisted_trunk-ssl_yes
        - env: TOX_ENV=pypy-twisted_trunk-ssl_no
        - env: TOX_ENV=pypy-twisted_trunk-ssl_yes
        - env: TOX_ENV=py33-twisted_trunk-ssl_no
        - env: TOX_ENV=py33-twisted_trunk-ssl_yes
        - env: TOX_ENV=py34-twisted_trunk-ssl_no
        - env: TOX_ENV=py34-twisted_trunk-ssl_yes

script:
    - tox -e "${TOX_ENV}"
    - ./runintegrations.sh

after_success:
    - coveralls
